---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(lubridate)
library(dplyr)
```
```{r}
cpi_by_region <- read_csv("../data/cpi_by_region.csv")
family_income <- read_csv("../data/income_updated.csv")
accurate_income <- read_csv("../data/accurate_income.csv")
cpi_total <- read_csv("../data/all_cpi_updated.csv")
cpi_income <- read_csv("../data/cpi_income.csv")
```

```{r}
cpi_by_region
```






```{r}
cpi_by_region <- cpi_by_region |>
  mutate(date = mdy(paste(Month, "01", Period)))
```


```{r}
min_year = 1990
max_year = 2000

cpi_by_region |>
  filter(Period >= min_year, Period <= max_year)
```

```{r}
min_year = 1980
max_year = 2005

cpi_by_region |>
  filter(Period >= min_year, Period <= max_year) |>
  ggplot(aes(x = date, y = CPI, group = Region, color = Region,linetype = Region)) +
  geom_line() +
  scale_color_manual(values = c('Red','Dark Green', 'Purple', 'Black', 'Blue')) +
  scale_linetype_manual(values = c("solid","solid", "solid", "dashed","solid"))
```
```{r}
family_income
```

```{r}
min_year = 1960
max_year = 2000
accurate_income |>
  filter(year >= min_year, year <= max_year) #|>
  #ggplot(aes(x = year, y= median_income))+
   #   geom_line()
       
```

```{r}
cpi_by_region |>
  group_by(Region)
```
```{r}
cpi_total |>
  ggplot(aes(x = year, y = CPI)) +
  geom_line()
```
```{r}
cpi_income |>
  ggplot(aes(x= year, y = yearly_change_c)) +
  geom_line()
```
```{r}
cpi_income |>
  ggplot(aes(x= year, y = yearly_change_i)) +
  geom_line()
```

```{r}
cpi_income |>
  ggplot(aes(x= year, y = cum_income_change)) +
  geom_line()
```
```{r}
cpi_income |>
  ggplot(aes(x= year, y = cum_cpi_change)) +
  geom_line()
```
```{r}
min_year = 2000
max_year = 2020

adjustable_cpi_income <- cpi_income |>
  filter(year >= min_year, year <= max_year)

adjustable_cpi_income <- adjustable_cpi_income |>
  mutate(cum_yearly_change_c = cumsum(yearly_change_c))

adjustable_cpi_income |>
  ggplot(aes(x = year, y = cum_yearly_change_c)) +
  geom_line()
```

